bottom:
  gelsight: "/bottom/gelsight/phi"
  vicon: "/bottom/vicon/phi"
  B_matrix: "Bcb.csv"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_bottom/command"
    reading: "/ethercat_master/Maxon_Motor_bottom/reading"
    state: "/bottom/Maxon_Motor/state"
top:
  B_matrix: "Bct.csv"
  gelsight: "/top/gelsight/phi"
  vicon: "/top/vicon/phi"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_top/command"
    reading: "/ethercat_master/Maxon_Motor_top/reading"
    state: "/top/Maxon_Motor/state"

matrices_path: "data/matrices/"
gelsight:
  rgb: "/gelsight/rgb"
vicon:
  pendulum: "/vicon/benjamin_v2/Root"
  world: "/vicon/benjamin_v2/World"
  downsample_factor: 10

limits:
  x: 51000
  dx: 10000

Ts: 0.01