bottom:
  B_matrix: "Bcb.csv"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_bottom/command"
    reading: "/ethercat_master/Maxon_Motor_bottom/reading"
    state: "/Maxon_Motor_bottom/state"
top:
  B_matrix: "Bct.csv"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_top/command"
    reading: "/ethercat_master/Maxon_Motor_top/reading"
    state: "/Maxon_Motor_top/state"

matrices_path: "data/matrices/"

limits:
  x: 51000
  dx: 10000

Ts: 0.01