topics:
  gelsight:
    rgb: "/gelsight/rgb"
    angles: "/gelsight/angles"
    anglesD: "/gelsight/anglesD"
  vicon:
    angles: "/vicon/angles"
    anglesD: "/vicon/anglesD"
  # these might change depending on the vicon setup
    state: "/vicon/benjamin_v2/Root"
    world: "/vicon/benjamin_v2/World"
  
  position:
    top: "/top/x"
    bottom: "/bottom/x"
  velocity:
    top: "/top/xD"
    bottom: "/bottom/xD"

  control:
    state: 
      bottom: "/bottom/state"
      top: "/top/state"
    set_state:
      bottom: "/bottom/set_state"
      top: "/top/set_state"
    measurement:
      bottom: "/bottom/y"
      top: "/top/y"
    command:
      bottom: "/bottom/v_sp"
      top: "/top/v_sp"

bottom:
  B_matrix: "Bcb.csv"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_bottom/command"
    reading: "/ethercat_master/Maxon_Motor_bottom/reading"
    state: "/Maxon_Motor_bottom/state"
top:
  B_matrix: "Bct.csv"
  Maxon_Motor:
    command: "/ethercat_master/Maxon_Motor_top/command"
    reading: "/ethercat_master/Maxon_Motor_top/reading"
    state: "/Maxon_Motor_top/state"

matrices_path: "data/matrices"

limits:
  x: 51000
  dx: 10000